name: "Generate Refit Client SDK using Refitter"
description: "Generates a Refit Client SDK using Refitter from an OpenAPI Specifications file"

inputs:
  openapi-url:
    description: If set, the OpenAPI document will be loaded from this URL instead of openapi-file.
    required: false
  openapi-file:
    description: The path to the OpenAPI document to generate a client library for
    required: false
    default: openapi.json
  namespace:
    description: The default namespace used for the generated types
    required: false   
  use-api-response:
    description: Return Task<IApiResponse<T>> instead of Task<T>
    required: false
    default: false
    type: boolean
  cancellation-tokens:
    description: Use cancellation tokens
    required: false
    default: false
    type: boolean
  command-args:
    description: Optional, additional arguments to pass through to Refitter
    required: false
    type: string
  publish-artifacts:
    description: Setting this will publish the generated code as C# files
    required: false
    type: boolean
    default: true
  client-sdk:
    description: Setting this will publish the generated code as a NuGet package
    required: false
    type: boolean
    default: false
  client-sdk-version:
    description: The version number used for the NuGet package
    required: false
    type: string
    default: 1.0.${{ github.run_number }}
  client-sdk-target-framework:
    description: The target framework used in the Client SDK
    required: false
    type: string
    default: net6.0
  client-sdk-package-id:
    required: false
    type: string
  client-sdk-title:
    required: false
    type: string
  client-sdk-root-namespace:
    required: false
    type: string
  client-sdk-assembly:
    required: false
    type: string
  client-sdk-authors:
    required: false
    type: string
  client-sdk-product:
    required: false
    type: string
  client-sdk-company:
    required: false
    type: string
  client-sdk-description:
    required: false
    type: string
  client-sdk-project-url:
    required: false
    type: string
  client-sdk-license:
    required: false
    type: string
    default: GPL-3.0-only
  client-sdk-repository-type:
    required: false
    type: string
    default: git
    

runs:
  using: composite
  steps:
    - name: Install Refitter
      run: dotnet tool install --global refitter
      shell: pwsh

    - name: Generate Client Interface
      run: |
        $input = ""
        if ("${{ inputs.openapi-url }}") {
          $input = "${{ inputs.openapi-url }}"
        } else {
          $input = "${{ inputs.openapi-file }}"
        }
        $args = ""
        if ("${{ inputs.namespace }}") {
          $args = "$args --namespace ${{ inputs.namespace }}"
        }
        if ($${{ inputs.use-api-response }}) {
          $args = "$args --use-api-response"
        }
        if ($${{ inputs.cancellation-tokens }}) {
          $args = "$args --cancellation-tokens"
        }
        Write-Host "refitter $input $args ${{ inputs.command-args }}"
        refitter $input $args ${{ inputs.command-args }}
      shell: pwsh

    - name: Publish Generated Code Artifacts
      if: ${{ inputs.publish-artifacts }}
      uses: actions/upload-artifact@v3
      with:
        name: Refit C# Client Code
        path: |
          **/*.cs

    - name: Generated C# project
      if: ${{ inputs.build-client-sdk }}
      run: |
        @'
        <Project Sdk="Microsoft.NET.Sdk">
          <PropertyGroup>
            <TargetFramework>${{ inputs.client-sdk-target-framework }}</TargetFramework>
            <LangVersion>latest</LangVersion>
            <Nullable>enable</Nullable>
            <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
            <Authors>${{ inputs.client-sdk-authors }}</Authors>
            <Product>${{ inputs.client-sdk-product }}</Product>
            <PackageId>${{ inputs.client-sdk-package-id }}</PackageId>
            <AssemblyName>${{ inputs.client-sdk-assembly }}</AssemblyName>
            <Company>${{ inputs.client-sdk-company }}</Company>
            <Description>${{ inputs.client-sdk-description }}</Description>
            <PackageLicenseExpression>${{ inputs.client-sdk-license }}</PackageLicenseExpression>
            <PackageProjectUrl>${{ inputs.client-sdk-project-url }}</PackageProjectUrl>
            <RepositoryUrl>${{ inputs.client-sdk-project-url }}</RepositoryUrl>
            <RepositoryType>${{ inputs.client-sdk-repository-type }}</RepositoryType>
            <PublishRepositoryUrl>true</PublishRepositoryUrl>
            <DebugType>embedded</DebugType>
            <EmbedUntrackedSources>true</EmbedUntrackedSources>
            <IsPackable>true</IsPackable>
            <TieredCompilation>true</TieredCompilation>
          </PropertyGroup>
          <ItemGroup>
            <PackageReference Include="Refit" Version="6.3.2" />
            <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
            <PackageReference Include="System.ComponentModel.Annotations" Version="4.5.0" />
            <PackageReference Include="System.Runtime.Serialization.Primitives" Version="4.3.0" />
          </ItemGroup>
        </Project>
        '@ | Out-File Build.csproj
        Get-Content Build.csproj | Write-Host
      shell: pwsh

    - name: Build
      if: ${{ inputs.build-client-sdk }}
      run: dotnet build -c Release /p:UseSourceLink=true -p:PackageVersion="${{ inputs.client-sdk-version }}"
      shell: pwsh

    - name: Pack
      if: ${{ inputs.build-client-sdk }}
      run: dotnet pack --no-build -c Release /p:UseSourceLink=true -p:PackageVersion="${{ inputs.client-sdk-version }}" --output .
      shell: pwsh

    - name: Publish Client SDK Artifact
      if: ${{ inputs.build-client-sdk }}
      uses: actions/upload-artifact@v3
      with:
        name: Refit Client SDK (NuGet)
        path: |
          **/*.nupkg
