name: Smoke Tests

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  smoke-test-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: christianhelle/refitter-action@main
        name: URI test
        with:
          openapi-url: https://petstore3.swagger.io/api/v3/openapi.json
          command-args: --no-logging
      - run: Get-Content Output.cs | Write-Host
        shell: pwsh